<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: waves/block.proto

namespace Waves\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>waves.Block</code>
 */
class Block extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.waves.Block.Header header = 1;</code>
     */
    protected $header = null;
    /**
     * Generated from protobuf field <code>bytes signature = 2;</code>
     */
    protected $signature = '';
    /**
     * Generated from protobuf field <code>repeated .waves.SignedTransaction transactions = 3;</code>
     */
    private $transactions;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Waves\Protobuf\Block\Header $header
     *     @type string $signature
     *     @type \Waves\Protobuf\SignedTransaction[] $transactions
     * }
     */
    public function __construct($data = NULL) {
        \Waves\ProtobufMetadata\Block::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.waves.Block.Header header = 1;</code>
     * @return \Waves\Protobuf\Block\Header|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     * Generated from protobuf field <code>.waves.Block.Header header = 1;</code>
     * @param \Waves\Protobuf\Block\Header $var
     * @return $this
     */
    public function setHeader(\Waves\Protobuf\Block\Header|null $var)
    {
        $this->header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes signature = 2;</code>
     * @return string
     */
    public function getSignature()
    {
        return $this->signature;
    }

    /**
     * Generated from protobuf field <code>bytes signature = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSignature(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->signature = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.SignedTransaction transactions = 3;</code>
     * @return RepeatedField<\Waves\Protobuf\SignedTransaction>
     */
    public function getTransactions()
    {
        return $this->transactions;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.SignedTransaction transactions = 3;</code>
     * @param \Waves\Protobuf\SignedTransaction[] $var
     * @return $this
     */
    public function setTransactions(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Waves\Protobuf\SignedTransaction::class);
        $this->transactions = $arr;

        return $this;
    }

}

