<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: waves/transaction.proto

namespace Waves\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>waves.CommitToGenerationTransactionData</code>
 */
class CommitToGenerationTransactionData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 generation_period_start = 1;</code>
     */
    protected $generation_period_start = 0;
    /**
     * BLS
     *
     * Generated from protobuf field <code>bytes endorser_public_key = 2;</code>
     */
    protected $endorser_public_key = '';
    /**
     * BLS signature for endorser_public_key ++ generation_period_start
     *
     * Generated from protobuf field <code>bytes commitment_signature = 3;</code>
     */
    protected $commitment_signature = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $generation_period_start
     *     @type string $endorser_public_key
     *           BLS
     *     @type string $commitment_signature
     *           BLS signature for endorser_public_key ++ generation_period_start
     * }
     */
    public function __construct($data = NULL) {
        \Waves\ProtobufMetadata\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 generation_period_start = 1;</code>
     * @return int
     */
    public function getGenerationPeriodStart()
    {
        return $this->generation_period_start;
    }

    /**
     * Generated from protobuf field <code>uint32 generation_period_start = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setGenerationPeriodStart(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->generation_period_start = $var;

        return $this;
    }

    /**
     * BLS
     *
     * Generated from protobuf field <code>bytes endorser_public_key = 2;</code>
     * @return string
     */
    public function getEndorserPublicKey()
    {
        return $this->endorser_public_key;
    }

    /**
     * BLS
     *
     * Generated from protobuf field <code>bytes endorser_public_key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEndorserPublicKey(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->endorser_public_key = $var;

        return $this;
    }

    /**
     * BLS signature for endorser_public_key ++ generation_period_start
     *
     * Generated from protobuf field <code>bytes commitment_signature = 3;</code>
     * @return string
     */
    public function getCommitmentSignature()
    {
        return $this->commitment_signature;
    }

    /**
     * BLS signature for endorser_public_key ++ generation_period_start
     *
     * Generated from protobuf field <code>bytes commitment_signature = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCommitmentSignature(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->commitment_signature = $var;

        return $this;
    }

}

