<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: waves/block.proto

namespace Waves\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>waves.EndorseBlock</code>
 */
class EndorseBlock extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 endorser_index = 1;</code>
     */
    protected $endorser_index = 0;
    /**
     * Generated from protobuf field <code>bytes finalized_block_id = 2;</code>
     */
    protected $finalized_block_id = '';
    /**
     * Generated from protobuf field <code>uint32 finalized_block_height = 3;</code>
     */
    protected $finalized_block_height = 0;
    /**
     * Generated from protobuf field <code>bytes endorsed_block_id = 4;</code>
     */
    protected $endorsed_block_id = '';
    /**
     * BLS
     *
     * Generated from protobuf field <code>bytes signature = 5;</code>
     */
    protected $signature = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $endorser_index
     *     @type string $finalized_block_id
     *     @type int $finalized_block_height
     *     @type string $endorsed_block_id
     *     @type string $signature
     *           BLS
     * }
     */
    public function __construct($data = NULL) {
        \Waves\ProtobufMetadata\Block::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 endorser_index = 1;</code>
     * @return int
     */
    public function getEndorserIndex()
    {
        return $this->endorser_index;
    }

    /**
     * Generated from protobuf field <code>int32 endorser_index = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setEndorserIndex(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->endorser_index = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes finalized_block_id = 2;</code>
     * @return string
     */
    public function getFinalizedBlockId()
    {
        return $this->finalized_block_id;
    }

    /**
     * Generated from protobuf field <code>bytes finalized_block_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFinalizedBlockId(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->finalized_block_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 finalized_block_height = 3;</code>
     * @return int
     */
    public function getFinalizedBlockHeight()
    {
        return $this->finalized_block_height;
    }

    /**
     * Generated from protobuf field <code>uint32 finalized_block_height = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setFinalizedBlockHeight(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->finalized_block_height = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes endorsed_block_id = 4;</code>
     * @return string
     */
    public function getEndorsedBlockId()
    {
        return $this->endorsed_block_id;
    }

    /**
     * Generated from protobuf field <code>bytes endorsed_block_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setEndorsedBlockId(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->endorsed_block_id = $var;

        return $this;
    }

    /**
     * BLS
     *
     * Generated from protobuf field <code>bytes signature = 5;</code>
     * @return string
     */
    public function getSignature()
    {
        return $this->signature;
    }

    /**
     * BLS
     *
     * Generated from protobuf field <code>bytes signature = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setSignature(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->signature = $var;

        return $this;
    }

}

