<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: waves/block.proto

namespace Waves\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>waves.FinalizationVoting</code>
 */
class FinalizationVoting extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated int32 endorser_indexes = 1;</code>
     */
    private $endorser_indexes;
    /**
     * Generated from protobuf field <code>int32 finalized_block_height = 2;</code>
     */
    protected $finalized_block_height = 0;
    /**
     * BLS
     *
     * Generated from protobuf field <code>bytes aggregated_endorsement_signature = 3;</code>
     */
    protected $aggregated_endorsement_signature = '';
    /**
     * Generated from protobuf field <code>repeated .waves.EndorseBlock conflict_endorsements = 4;</code>
     */
    private $conflict_endorsements;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int[] $endorser_indexes
     *     @type int $finalized_block_height
     *     @type string $aggregated_endorsement_signature
     *           BLS
     *     @type \Waves\Protobuf\EndorseBlock[] $conflict_endorsements
     * }
     */
    public function __construct($data = NULL) {
        \Waves\ProtobufMetadata\Block::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated int32 endorser_indexes = 1;</code>
     * @return RepeatedField<int>
     */
    public function getEndorserIndexes()
    {
        return $this->endorser_indexes;
    }

    /**
     * Generated from protobuf field <code>repeated int32 endorser_indexes = 1;</code>
     * @param int[] $var
     * @return $this
     */
    public function setEndorserIndexes(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->endorser_indexes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 finalized_block_height = 2;</code>
     * @return int
     */
    public function getFinalizedBlockHeight()
    {
        return $this->finalized_block_height;
    }

    /**
     * Generated from protobuf field <code>int32 finalized_block_height = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setFinalizedBlockHeight(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->finalized_block_height = $var;

        return $this;
    }

    /**
     * BLS
     *
     * Generated from protobuf field <code>bytes aggregated_endorsement_signature = 3;</code>
     * @return string
     */
    public function getAggregatedEndorsementSignature()
    {
        return $this->aggregated_endorsement_signature;
    }

    /**
     * BLS
     *
     * Generated from protobuf field <code>bytes aggregated_endorsement_signature = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAggregatedEndorsementSignature(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->aggregated_endorsement_signature = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.EndorseBlock conflict_endorsements = 4;</code>
     * @return RepeatedField<\Waves\Protobuf\EndorseBlock>
     */
    public function getConflictEndorsements()
    {
        return $this->conflict_endorsements;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.EndorseBlock conflict_endorsements = 4;</code>
     * @param \Waves\Protobuf\EndorseBlock[] $var
     * @return $this
     */
    public function setConflictEndorsements(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Waves\Protobuf\EndorseBlock::class);
        $this->conflict_endorsements = $arr;

        return $this;
    }

}

