<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: waves/invoke_script_result.proto

namespace Waves\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>waves.InvokeScriptResult</code>
 */
class InvokeScriptResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .waves.DataEntry data = 1;</code>
     */
    private $data;
    /**
     * Generated from protobuf field <code>repeated .waves.InvokeScriptResult.Payment transfers = 2;</code>
     */
    private $transfers;
    /**
     * Generated from protobuf field <code>repeated .waves.InvokeScriptResult.Issue issues = 3;</code>
     */
    private $issues;
    /**
     * Generated from protobuf field <code>repeated .waves.InvokeScriptResult.Reissue reissues = 4;</code>
     */
    private $reissues;
    /**
     * Generated from protobuf field <code>repeated .waves.InvokeScriptResult.Burn burns = 5;</code>
     */
    private $burns;
    /**
     * Generated from protobuf field <code>.waves.InvokeScriptResult.ErrorMessage error_message = 6;</code>
     */
    protected $error_message = null;
    /**
     * Generated from protobuf field <code>repeated .waves.InvokeScriptResult.SponsorFee sponsor_fees = 7;</code>
     */
    private $sponsor_fees;
    /**
     * Generated from protobuf field <code>repeated .waves.InvokeScriptResult.Lease leases = 8;</code>
     */
    private $leases;
    /**
     * Generated from protobuf field <code>repeated .waves.InvokeScriptResult.LeaseCancel lease_cancels = 9;</code>
     */
    private $lease_cancels;
    /**
     * Generated from protobuf field <code>repeated .waves.InvokeScriptResult.Invocation invokes = 10;</code>
     */
    private $invokes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Waves\Protobuf\DataEntry[] $data
     *     @type \Waves\Protobuf\InvokeScriptResult\Payment[] $transfers
     *     @type \Waves\Protobuf\InvokeScriptResult\Issue[] $issues
     *     @type \Waves\Protobuf\InvokeScriptResult\Reissue[] $reissues
     *     @type \Waves\Protobuf\InvokeScriptResult\Burn[] $burns
     *     @type \Waves\Protobuf\InvokeScriptResult\ErrorMessage $error_message
     *     @type \Waves\Protobuf\InvokeScriptResult\SponsorFee[] $sponsor_fees
     *     @type \Waves\Protobuf\InvokeScriptResult\Lease[] $leases
     *     @type \Waves\Protobuf\InvokeScriptResult\LeaseCancel[] $lease_cancels
     *     @type \Waves\Protobuf\InvokeScriptResult\Invocation[] $invokes
     * }
     */
    public function __construct($data = NULL) {
        \Waves\ProtobufMetadata\InvokeScriptResult::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .waves.DataEntry data = 1;</code>
     * @return RepeatedField<\Waves\Protobuf\DataEntry>
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.DataEntry data = 1;</code>
     * @param \Waves\Protobuf\DataEntry[] $var
     * @return $this
     */
    public function setData(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Waves\Protobuf\DataEntry::class);
        $this->data = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.InvokeScriptResult.Payment transfers = 2;</code>
     * @return RepeatedField<\Waves\Protobuf\InvokeScriptResult\Payment>
     */
    public function getTransfers()
    {
        return $this->transfers;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.InvokeScriptResult.Payment transfers = 2;</code>
     * @param \Waves\Protobuf\InvokeScriptResult\Payment[] $var
     * @return $this
     */
    public function setTransfers(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Waves\Protobuf\InvokeScriptResult\Payment::class);
        $this->transfers = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.InvokeScriptResult.Issue issues = 3;</code>
     * @return RepeatedField<\Waves\Protobuf\InvokeScriptResult\Issue>
     */
    public function getIssues()
    {
        return $this->issues;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.InvokeScriptResult.Issue issues = 3;</code>
     * @param \Waves\Protobuf\InvokeScriptResult\Issue[] $var
     * @return $this
     */
    public function setIssues(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Waves\Protobuf\InvokeScriptResult\Issue::class);
        $this->issues = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.InvokeScriptResult.Reissue reissues = 4;</code>
     * @return RepeatedField<\Waves\Protobuf\InvokeScriptResult\Reissue>
     */
    public function getReissues()
    {
        return $this->reissues;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.InvokeScriptResult.Reissue reissues = 4;</code>
     * @param \Waves\Protobuf\InvokeScriptResult\Reissue[] $var
     * @return $this
     */
    public function setReissues(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Waves\Protobuf\InvokeScriptResult\Reissue::class);
        $this->reissues = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.InvokeScriptResult.Burn burns = 5;</code>
     * @return RepeatedField<\Waves\Protobuf\InvokeScriptResult\Burn>
     */
    public function getBurns()
    {
        return $this->burns;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.InvokeScriptResult.Burn burns = 5;</code>
     * @param \Waves\Protobuf\InvokeScriptResult\Burn[] $var
     * @return $this
     */
    public function setBurns(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Waves\Protobuf\InvokeScriptResult\Burn::class);
        $this->burns = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.waves.InvokeScriptResult.ErrorMessage error_message = 6;</code>
     * @return \Waves\Protobuf\InvokeScriptResult\ErrorMessage|null
     */
    public function getErrorMessage()
    {
        return $this->error_message;
    }

    public function hasErrorMessage()
    {
        return isset($this->error_message);
    }

    public function clearErrorMessage()
    {
        unset($this->error_message);
    }

    /**
     * Generated from protobuf field <code>.waves.InvokeScriptResult.ErrorMessage error_message = 6;</code>
     * @param \Waves\Protobuf\InvokeScriptResult\ErrorMessage $var
     * @return $this
     */
    public function setErrorMessage(\Waves\Protobuf\InvokeScriptResult\ErrorMessage|null $var)
    {
        $this->error_message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.InvokeScriptResult.SponsorFee sponsor_fees = 7;</code>
     * @return RepeatedField<\Waves\Protobuf\InvokeScriptResult\SponsorFee>
     */
    public function getSponsorFees()
    {
        return $this->sponsor_fees;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.InvokeScriptResult.SponsorFee sponsor_fees = 7;</code>
     * @param \Waves\Protobuf\InvokeScriptResult\SponsorFee[] $var
     * @return $this
     */
    public function setSponsorFees(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Waves\Protobuf\InvokeScriptResult\SponsorFee::class);
        $this->sponsor_fees = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.InvokeScriptResult.Lease leases = 8;</code>
     * @return RepeatedField<\Waves\Protobuf\InvokeScriptResult\Lease>
     */
    public function getLeases()
    {
        return $this->leases;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.InvokeScriptResult.Lease leases = 8;</code>
     * @param \Waves\Protobuf\InvokeScriptResult\Lease[] $var
     * @return $this
     */
    public function setLeases(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Waves\Protobuf\InvokeScriptResult\Lease::class);
        $this->leases = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.InvokeScriptResult.LeaseCancel lease_cancels = 9;</code>
     * @return RepeatedField<\Waves\Protobuf\InvokeScriptResult\LeaseCancel>
     */
    public function getLeaseCancels()
    {
        return $this->lease_cancels;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.InvokeScriptResult.LeaseCancel lease_cancels = 9;</code>
     * @param \Waves\Protobuf\InvokeScriptResult\LeaseCancel[] $var
     * @return $this
     */
    public function setLeaseCancels(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Waves\Protobuf\InvokeScriptResult\LeaseCancel::class);
        $this->lease_cancels = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.InvokeScriptResult.Invocation invokes = 10;</code>
     * @return RepeatedField<\Waves\Protobuf\InvokeScriptResult\Invocation>
     */
    public function getInvokes()
    {
        return $this->invokes;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.InvokeScriptResult.Invocation invokes = 10;</code>
     * @param \Waves\Protobuf\InvokeScriptResult\Invocation[] $var
     * @return $this
     */
    public function setInvokes(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Waves\Protobuf\InvokeScriptResult\Invocation::class);
        $this->invokes = $arr;

        return $this;
    }

}

