<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: waves/block.proto

namespace Waves\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>waves.MicroBlock</code>
 */
class MicroBlock extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 version = 1;</code>
     */
    protected $version = 0;
    /**
     * Generated from protobuf field <code>bytes reference = 2;</code>
     */
    protected $reference = '';
    /**
     * Generated from protobuf field <code>bytes updated_block_signature = 3;</code>
     */
    protected $updated_block_signature = '';
    /**
     * Generated from protobuf field <code>bytes sender_public_key = 4;</code>
     */
    protected $sender_public_key = '';
    /**
     * Generated from protobuf field <code>repeated .waves.SignedTransaction transactions = 5;</code>
     */
    private $transactions;
    /**
     * Generated from protobuf field <code>bytes state_hash = 6;</code>
     */
    protected $state_hash = '';
    /**
     * Generated from protobuf field <code>.waves.FinalizationVoting finalization_voting = 7;</code>
     */
    protected $finalization_voting = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $version
     *     @type string $reference
     *     @type string $updated_block_signature
     *     @type string $sender_public_key
     *     @type \Waves\Protobuf\SignedTransaction[] $transactions
     *     @type string $state_hash
     *     @type \Waves\Protobuf\FinalizationVoting $finalization_voting
     * }
     */
    public function __construct($data = NULL) {
        \Waves\ProtobufMetadata\Block::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 version = 1;</code>
     * @return int
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>int32 version = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setVersion(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes reference = 2;</code>
     * @return string
     */
    public function getReference()
    {
        return $this->reference;
    }

    /**
     * Generated from protobuf field <code>bytes reference = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setReference(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->reference = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes updated_block_signature = 3;</code>
     * @return string
     */
    public function getUpdatedBlockSignature()
    {
        return $this->updated_block_signature;
    }

    /**
     * Generated from protobuf field <code>bytes updated_block_signature = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUpdatedBlockSignature(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->updated_block_signature = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes sender_public_key = 4;</code>
     * @return string
     */
    public function getSenderPublicKey()
    {
        return $this->sender_public_key;
    }

    /**
     * Generated from protobuf field <code>bytes sender_public_key = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSenderPublicKey(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->sender_public_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.SignedTransaction transactions = 5;</code>
     * @return RepeatedField<\Waves\Protobuf\SignedTransaction>
     */
    public function getTransactions()
    {
        return $this->transactions;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.SignedTransaction transactions = 5;</code>
     * @param \Waves\Protobuf\SignedTransaction[] $var
     * @return $this
     */
    public function setTransactions(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Waves\Protobuf\SignedTransaction::class);
        $this->transactions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes state_hash = 6;</code>
     * @return string
     */
    public function getStateHash()
    {
        return $this->state_hash;
    }

    /**
     * Generated from protobuf field <code>bytes state_hash = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setStateHash(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->state_hash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.waves.FinalizationVoting finalization_voting = 7;</code>
     * @return \Waves\Protobuf\FinalizationVoting|null
     */
    public function getFinalizationVoting()
    {
        return $this->finalization_voting;
    }

    public function hasFinalizationVoting()
    {
        return isset($this->finalization_voting);
    }

    public function clearFinalizationVoting()
    {
        unset($this->finalization_voting);
    }

    /**
     * Generated from protobuf field <code>.waves.FinalizationVoting finalization_voting = 7;</code>
     * @param \Waves\Protobuf\FinalizationVoting $var
     * @return $this
     */
    public function setFinalizationVoting(\Waves\Protobuf\FinalizationVoting|null $var)
    {
        $this->finalization_voting = $var;

        return $this;
    }

}

