<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: waves/state_snapshot.proto

namespace Waves\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>waves.MicroBlockSnapshot</code>
 */
class MicroBlockSnapshot extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes total_block_id = 1;</code>
     */
    protected $total_block_id = '';
    /**
     * Generated from protobuf field <code>repeated .waves.TransactionStateSnapshot snapshots = 2;</code>
     */
    private $snapshots;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $total_block_id
     *     @type \Waves\Protobuf\TransactionStateSnapshot[] $snapshots
     * }
     */
    public function __construct($data = NULL) {
        \Waves\ProtobufMetadata\StateSnapshot::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes total_block_id = 1;</code>
     * @return string
     */
    public function getTotalBlockId()
    {
        return $this->total_block_id;
    }

    /**
     * Generated from protobuf field <code>bytes total_block_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTotalBlockId(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->total_block_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.TransactionStateSnapshot snapshots = 2;</code>
     * @return RepeatedField<\Waves\Protobuf\TransactionStateSnapshot>
     */
    public function getSnapshots()
    {
        return $this->snapshots;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.TransactionStateSnapshot snapshots = 2;</code>
     * @param \Waves\Protobuf\TransactionStateSnapshot[] $var
     * @return $this
     */
    public function setSnapshots(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Waves\Protobuf\TransactionStateSnapshot::class);
        $this->snapshots = $arr;

        return $this;
    }

}

