<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: waves/transaction.proto

namespace Waves\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>waves.SignedTransaction</code>
 */
class SignedTransaction extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated bytes proofs = 2;</code>
     */
    private $proofs;
    protected $transaction;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Waves\Protobuf\Transaction $waves_transaction
     *     @type string $ethereum_transaction
     *     @type string[] $proofs
     * }
     */
    public function __construct($data = NULL) {
        \Waves\ProtobufMetadata\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.waves.Transaction waves_transaction = 1;</code>
     * @return \Waves\Protobuf\Transaction|null
     */
    public function getWavesTransaction()
    {
        return $this->readOneof(1);
    }

    public function hasWavesTransaction()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.waves.Transaction waves_transaction = 1;</code>
     * @param \Waves\Protobuf\Transaction $var
     * @return $this
     */
    public function setWavesTransaction(\Waves\Protobuf\Transaction|null $var)
    {
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes ethereum_transaction = 3;</code>
     * @return string
     */
    public function getEthereumTransaction()
    {
        return $this->readOneof(3);
    }

    public function hasEthereumTransaction()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>bytes ethereum_transaction = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setEthereumTransaction(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes proofs = 2;</code>
     * @return RepeatedField<string>
     */
    public function getProofs()
    {
        return $this->proofs;
    }

    /**
     * Generated from protobuf field <code>repeated bytes proofs = 2;</code>
     * @param string[] $var
     * @return $this
     */
    public function setProofs(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->proofs = $arr;

        return $this;
    }

    /**
     * @return string
     */
    public function getTransaction()
    {
        return $this->whichOneof("transaction");
    }

}

