<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: waves/transaction_state_snapshot.proto

namespace Waves\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>waves.TransactionStateSnapshot</code>
 */
class TransactionStateSnapshot extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .waves.TransactionStateSnapshot.Balance balances = 1;</code>
     */
    private $balances;
    /**
     * Generated from protobuf field <code>repeated .waves.TransactionStateSnapshot.LeaseBalance lease_balances = 2;</code>
     */
    private $lease_balances;
    /**
     * Generated from protobuf field <code>repeated .waves.TransactionStateSnapshot.NewLease new_leases = 3;</code>
     */
    private $new_leases;
    /**
     * Generated from protobuf field <code>repeated .waves.TransactionStateSnapshot.CancelledLease cancelled_leases = 4;</code>
     */
    private $cancelled_leases;
    /**
     * Generated from protobuf field <code>repeated .waves.TransactionStateSnapshot.NewAsset asset_statics = 5;</code>
     */
    private $asset_statics;
    /**
     * Generated from protobuf field <code>repeated .waves.TransactionStateSnapshot.AssetVolume asset_volumes = 6;</code>
     */
    private $asset_volumes;
    /**
     * Generated from protobuf field <code>repeated .waves.TransactionStateSnapshot.AssetNameAndDescription asset_names_and_descriptions = 7;</code>
     */
    private $asset_names_and_descriptions;
    /**
     * Generated from protobuf field <code>.waves.TransactionStateSnapshot.AssetScript asset_scripts = 8;</code>
     */
    protected $asset_scripts = null;
    /**
     * Generated from protobuf field <code>.waves.TransactionStateSnapshot.Alias aliases = 9;</code>
     */
    protected $aliases = null;
    /**
     * Generated from protobuf field <code>repeated .waves.TransactionStateSnapshot.OrderFill order_fills = 10;</code>
     */
    private $order_fills;
    /**
     * Generated from protobuf field <code>.waves.TransactionStateSnapshot.AccountScript account_scripts = 11;</code>
     */
    protected $account_scripts = null;
    /**
     * Generated from protobuf field <code>repeated .waves.TransactionStateSnapshot.AccountData account_data = 12;</code>
     */
    private $account_data;
    /**
     * Generated from protobuf field <code>repeated .waves.TransactionStateSnapshot.Sponsorship sponsorships = 13;</code>
     */
    private $sponsorships;
    /**
     * Generated from protobuf field <code>.waves.TransactionStatus transaction_status = 14;</code>
     */
    protected $transaction_status = 0;
    /**
     * Generated from protobuf field <code>.waves.TransactionStateSnapshot.GenerationCommitment generation_commitment = 15;</code>
     */
    protected $generation_commitment = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Waves\Protobuf\TransactionStateSnapshot\Balance[] $balances
     *     @type \Waves\Protobuf\TransactionStateSnapshot\LeaseBalance[] $lease_balances
     *     @type \Waves\Protobuf\TransactionStateSnapshot\NewLease[] $new_leases
     *     @type \Waves\Protobuf\TransactionStateSnapshot\CancelledLease[] $cancelled_leases
     *     @type \Waves\Protobuf\TransactionStateSnapshot\NewAsset[] $asset_statics
     *     @type \Waves\Protobuf\TransactionStateSnapshot\AssetVolume[] $asset_volumes
     *     @type \Waves\Protobuf\TransactionStateSnapshot\AssetNameAndDescription[] $asset_names_and_descriptions
     *     @type \Waves\Protobuf\TransactionStateSnapshot\AssetScript $asset_scripts
     *     @type \Waves\Protobuf\TransactionStateSnapshot\Alias $aliases
     *     @type \Waves\Protobuf\TransactionStateSnapshot\OrderFill[] $order_fills
     *     @type \Waves\Protobuf\TransactionStateSnapshot\AccountScript $account_scripts
     *     @type \Waves\Protobuf\TransactionStateSnapshot\AccountData[] $account_data
     *     @type \Waves\Protobuf\TransactionStateSnapshot\Sponsorship[] $sponsorships
     *     @type int $transaction_status
     *     @type \Waves\Protobuf\TransactionStateSnapshot\GenerationCommitment $generation_commitment
     * }
     */
    public function __construct($data = NULL) {
        \Waves\ProtobufMetadata\TransactionStateSnapshot::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .waves.TransactionStateSnapshot.Balance balances = 1;</code>
     * @return RepeatedField<\Waves\Protobuf\TransactionStateSnapshot\Balance>
     */
    public function getBalances()
    {
        return $this->balances;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.TransactionStateSnapshot.Balance balances = 1;</code>
     * @param \Waves\Protobuf\TransactionStateSnapshot\Balance[] $var
     * @return $this
     */
    public function setBalances(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Waves\Protobuf\TransactionStateSnapshot\Balance::class);
        $this->balances = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.TransactionStateSnapshot.LeaseBalance lease_balances = 2;</code>
     * @return RepeatedField<\Waves\Protobuf\TransactionStateSnapshot\LeaseBalance>
     */
    public function getLeaseBalances()
    {
        return $this->lease_balances;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.TransactionStateSnapshot.LeaseBalance lease_balances = 2;</code>
     * @param \Waves\Protobuf\TransactionStateSnapshot\LeaseBalance[] $var
     * @return $this
     */
    public function setLeaseBalances(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Waves\Protobuf\TransactionStateSnapshot\LeaseBalance::class);
        $this->lease_balances = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.TransactionStateSnapshot.NewLease new_leases = 3;</code>
     * @return RepeatedField<\Waves\Protobuf\TransactionStateSnapshot\NewLease>
     */
    public function getNewLeases()
    {
        return $this->new_leases;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.TransactionStateSnapshot.NewLease new_leases = 3;</code>
     * @param \Waves\Protobuf\TransactionStateSnapshot\NewLease[] $var
     * @return $this
     */
    public function setNewLeases(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Waves\Protobuf\TransactionStateSnapshot\NewLease::class);
        $this->new_leases = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.TransactionStateSnapshot.CancelledLease cancelled_leases = 4;</code>
     * @return RepeatedField<\Waves\Protobuf\TransactionStateSnapshot\CancelledLease>
     */
    public function getCancelledLeases()
    {
        return $this->cancelled_leases;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.TransactionStateSnapshot.CancelledLease cancelled_leases = 4;</code>
     * @param \Waves\Protobuf\TransactionStateSnapshot\CancelledLease[] $var
     * @return $this
     */
    public function setCancelledLeases(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Waves\Protobuf\TransactionStateSnapshot\CancelledLease::class);
        $this->cancelled_leases = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.TransactionStateSnapshot.NewAsset asset_statics = 5;</code>
     * @return RepeatedField<\Waves\Protobuf\TransactionStateSnapshot\NewAsset>
     */
    public function getAssetStatics()
    {
        return $this->asset_statics;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.TransactionStateSnapshot.NewAsset asset_statics = 5;</code>
     * @param \Waves\Protobuf\TransactionStateSnapshot\NewAsset[] $var
     * @return $this
     */
    public function setAssetStatics(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Waves\Protobuf\TransactionStateSnapshot\NewAsset::class);
        $this->asset_statics = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.TransactionStateSnapshot.AssetVolume asset_volumes = 6;</code>
     * @return RepeatedField<\Waves\Protobuf\TransactionStateSnapshot\AssetVolume>
     */
    public function getAssetVolumes()
    {
        return $this->asset_volumes;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.TransactionStateSnapshot.AssetVolume asset_volumes = 6;</code>
     * @param \Waves\Protobuf\TransactionStateSnapshot\AssetVolume[] $var
     * @return $this
     */
    public function setAssetVolumes(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Waves\Protobuf\TransactionStateSnapshot\AssetVolume::class);
        $this->asset_volumes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.TransactionStateSnapshot.AssetNameAndDescription asset_names_and_descriptions = 7;</code>
     * @return RepeatedField<\Waves\Protobuf\TransactionStateSnapshot\AssetNameAndDescription>
     */
    public function getAssetNamesAndDescriptions()
    {
        return $this->asset_names_and_descriptions;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.TransactionStateSnapshot.AssetNameAndDescription asset_names_and_descriptions = 7;</code>
     * @param \Waves\Protobuf\TransactionStateSnapshot\AssetNameAndDescription[] $var
     * @return $this
     */
    public function setAssetNamesAndDescriptions(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Waves\Protobuf\TransactionStateSnapshot\AssetNameAndDescription::class);
        $this->asset_names_and_descriptions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.waves.TransactionStateSnapshot.AssetScript asset_scripts = 8;</code>
     * @return \Waves\Protobuf\TransactionStateSnapshot\AssetScript|null
     */
    public function getAssetScripts()
    {
        return $this->asset_scripts;
    }

    public function hasAssetScripts()
    {
        return isset($this->asset_scripts);
    }

    public function clearAssetScripts()
    {
        unset($this->asset_scripts);
    }

    /**
     * Generated from protobuf field <code>.waves.TransactionStateSnapshot.AssetScript asset_scripts = 8;</code>
     * @param \Waves\Protobuf\TransactionStateSnapshot\AssetScript $var
     * @return $this
     */
    public function setAssetScripts(\Waves\Protobuf\TransactionStateSnapshot\AssetScript|null $var)
    {
        $this->asset_scripts = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.waves.TransactionStateSnapshot.Alias aliases = 9;</code>
     * @return \Waves\Protobuf\TransactionStateSnapshot\Alias|null
     */
    public function getAliases()
    {
        return $this->aliases;
    }

    public function hasAliases()
    {
        return isset($this->aliases);
    }

    public function clearAliases()
    {
        unset($this->aliases);
    }

    /**
     * Generated from protobuf field <code>.waves.TransactionStateSnapshot.Alias aliases = 9;</code>
     * @param \Waves\Protobuf\TransactionStateSnapshot\Alias $var
     * @return $this
     */
    public function setAliases(\Waves\Protobuf\TransactionStateSnapshot\Alias|null $var)
    {
        $this->aliases = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.TransactionStateSnapshot.OrderFill order_fills = 10;</code>
     * @return RepeatedField<\Waves\Protobuf\TransactionStateSnapshot\OrderFill>
     */
    public function getOrderFills()
    {
        return $this->order_fills;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.TransactionStateSnapshot.OrderFill order_fills = 10;</code>
     * @param \Waves\Protobuf\TransactionStateSnapshot\OrderFill[] $var
     * @return $this
     */
    public function setOrderFills(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Waves\Protobuf\TransactionStateSnapshot\OrderFill::class);
        $this->order_fills = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.waves.TransactionStateSnapshot.AccountScript account_scripts = 11;</code>
     * @return \Waves\Protobuf\TransactionStateSnapshot\AccountScript|null
     */
    public function getAccountScripts()
    {
        return $this->account_scripts;
    }

    public function hasAccountScripts()
    {
        return isset($this->account_scripts);
    }

    public function clearAccountScripts()
    {
        unset($this->account_scripts);
    }

    /**
     * Generated from protobuf field <code>.waves.TransactionStateSnapshot.AccountScript account_scripts = 11;</code>
     * @param \Waves\Protobuf\TransactionStateSnapshot\AccountScript $var
     * @return $this
     */
    public function setAccountScripts(\Waves\Protobuf\TransactionStateSnapshot\AccountScript|null $var)
    {
        $this->account_scripts = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.TransactionStateSnapshot.AccountData account_data = 12;</code>
     * @return RepeatedField<\Waves\Protobuf\TransactionStateSnapshot\AccountData>
     */
    public function getAccountData()
    {
        return $this->account_data;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.TransactionStateSnapshot.AccountData account_data = 12;</code>
     * @param \Waves\Protobuf\TransactionStateSnapshot\AccountData[] $var
     * @return $this
     */
    public function setAccountData(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Waves\Protobuf\TransactionStateSnapshot\AccountData::class);
        $this->account_data = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.TransactionStateSnapshot.Sponsorship sponsorships = 13;</code>
     * @return RepeatedField<\Waves\Protobuf\TransactionStateSnapshot\Sponsorship>
     */
    public function getSponsorships()
    {
        return $this->sponsorships;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.TransactionStateSnapshot.Sponsorship sponsorships = 13;</code>
     * @param \Waves\Protobuf\TransactionStateSnapshot\Sponsorship[] $var
     * @return $this
     */
    public function setSponsorships(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Waves\Protobuf\TransactionStateSnapshot\Sponsorship::class);
        $this->sponsorships = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.waves.TransactionStatus transaction_status = 14;</code>
     * @return int one of the values in {@see \Waves\Protobuf\TransactionStatus}
     */
    public function getTransactionStatus()
    {
        return $this->transaction_status;
    }

    /**
     * Generated from protobuf field <code>.waves.TransactionStatus transaction_status = 14;</code>
     * @param int $var one of the values in {@see \Waves\Protobuf\TransactionStatus}
     * @return $this
     */
    public function setTransactionStatus(int $var)
    {
        GPBUtil::checkEnum($var, \Waves\Protobuf\TransactionStatus::class);
        $this->transaction_status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.waves.TransactionStateSnapshot.GenerationCommitment generation_commitment = 15;</code>
     * @return \Waves\Protobuf\TransactionStateSnapshot\GenerationCommitment|null
     */
    public function getGenerationCommitment()
    {
        return $this->generation_commitment;
    }

    public function hasGenerationCommitment()
    {
        return isset($this->generation_commitment);
    }

    public function clearGenerationCommitment()
    {
        unset($this->generation_commitment);
    }

    /**
     * Generated from protobuf field <code>.waves.TransactionStateSnapshot.GenerationCommitment generation_commitment = 15;</code>
     * @param \Waves\Protobuf\TransactionStateSnapshot\GenerationCommitment $var
     * @return $this
     */
    public function setGenerationCommitment(\Waves\Protobuf\TransactionStateSnapshot\GenerationCommitment|null $var)
    {
        $this->generation_commitment = $var;

        return $this;
    }

}

