<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: waves/block.proto

namespace Waves\Protobuf\Block\Header;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>waves.Block.Header.ChallengedHeader</code>
 */
class ChallengedHeader extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 base_target = 1;</code>
     */
    protected $base_target = 0;
    /**
     * Generated from protobuf field <code>bytes generation_signature = 2;</code>
     */
    protected $generation_signature = '';
    /**
     * Generated from protobuf field <code>repeated uint32 feature_votes = 3;</code>
     */
    private $feature_votes;
    /**
     * Generated from protobuf field <code>int64 timestamp = 4;</code>
     */
    protected $timestamp = 0;
    /**
     * Generated from protobuf field <code>bytes generator = 5;</code>
     */
    protected $generator = '';
    /**
     * Generated from protobuf field <code>int64 reward_vote = 6;</code>
     */
    protected $reward_vote = 0;
    /**
     * Generated from protobuf field <code>bytes state_hash = 7;</code>
     */
    protected $state_hash = '';
    /**
     * Generated from protobuf field <code>bytes header_signature = 8;</code>
     */
    protected $header_signature = '';
    /**
     * Generated from protobuf field <code>.waves.FinalizationVoting finalization_voting = 9;</code>
     */
    protected $finalization_voting = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $base_target
     *     @type string $generation_signature
     *     @type int[] $feature_votes
     *     @type int|string $timestamp
     *     @type string $generator
     *     @type int|string $reward_vote
     *     @type string $state_hash
     *     @type string $header_signature
     *     @type \Waves\Protobuf\FinalizationVoting $finalization_voting
     * }
     */
    public function __construct($data = NULL) {
        \Waves\ProtobufMetadata\Block::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 base_target = 1;</code>
     * @return int|string
     */
    public function getBaseTarget()
    {
        return $this->base_target;
    }

    /**
     * Generated from protobuf field <code>int64 base_target = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBaseTarget(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->base_target = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes generation_signature = 2;</code>
     * @return string
     */
    public function getGenerationSignature()
    {
        return $this->generation_signature;
    }

    /**
     * Generated from protobuf field <code>bytes generation_signature = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setGenerationSignature(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->generation_signature = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 feature_votes = 3;</code>
     * @return RepeatedField<int>
     */
    public function getFeatureVotes()
    {
        return $this->feature_votes;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 feature_votes = 3;</code>
     * @param int[] $var
     * @return $this
     */
    public function setFeatureVotes(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->feature_votes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 4;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes generator = 5;</code>
     * @return string
     */
    public function getGenerator()
    {
        return $this->generator;
    }

    /**
     * Generated from protobuf field <code>bytes generator = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setGenerator(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->generator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 reward_vote = 6;</code>
     * @return int|string
     */
    public function getRewardVote()
    {
        return $this->reward_vote;
    }

    /**
     * Generated from protobuf field <code>int64 reward_vote = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRewardVote(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->reward_vote = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes state_hash = 7;</code>
     * @return string
     */
    public function getStateHash()
    {
        return $this->state_hash;
    }

    /**
     * Generated from protobuf field <code>bytes state_hash = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setStateHash(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->state_hash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes header_signature = 8;</code>
     * @return string
     */
    public function getHeaderSignature()
    {
        return $this->header_signature;
    }

    /**
     * Generated from protobuf field <code>bytes header_signature = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setHeaderSignature(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->header_signature = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.waves.FinalizationVoting finalization_voting = 9;</code>
     * @return \Waves\Protobuf\FinalizationVoting|null
     */
    public function getFinalizationVoting()
    {
        return $this->finalization_voting;
    }

    public function hasFinalizationVoting()
    {
        return isset($this->finalization_voting);
    }

    public function clearFinalizationVoting()
    {
        unset($this->finalization_voting);
    }

    /**
     * Generated from protobuf field <code>.waves.FinalizationVoting finalization_voting = 9;</code>
     * @param \Waves\Protobuf\FinalizationVoting $var
     * @return $this
     */
    public function setFinalizationVoting(\Waves\Protobuf\FinalizationVoting|null $var)
    {
        $this->finalization_voting = $var;

        return $this;
    }

}

