<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: waves/transaction_state_snapshot.proto

namespace Waves\Protobuf\TransactionStateSnapshot;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>waves.TransactionStateSnapshot.GenerationCommitment</code>
 */
class GenerationCommitment extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes sender_public_key = 1;</code>
     */
    protected $sender_public_key = '';
    /**
     * Generated from protobuf field <code>bytes endorser_public_key = 2;</code>
     */
    protected $endorser_public_key = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $sender_public_key
     *     @type string $endorser_public_key
     * }
     */
    public function __construct($data = NULL) {
        \Waves\ProtobufMetadata\TransactionStateSnapshot::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes sender_public_key = 1;</code>
     * @return string
     */
    public function getSenderPublicKey()
    {
        return $this->sender_public_key;
    }

    /**
     * Generated from protobuf field <code>bytes sender_public_key = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSenderPublicKey(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->sender_public_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes endorser_public_key = 2;</code>
     * @return string
     */
    public function getEndorserPublicKey()
    {
        return $this->endorser_public_key;
    }

    /**
     * Generated from protobuf field <code>bytes endorser_public_key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEndorserPublicKey(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->endorser_public_key = $var;

        return $this;
    }

}

